### ISSUE TITLE
RK3568 compatibility

### ISSUE THREAD

**Issue by Salex406** [DualTachyon/rk3588-secure-boot#2]
Hello
What do you think, can it be compatible with RK3568?

**Comment by DualTachyon** [comment]
Hard to say, I don't have a RK3568 device. The logic might me highly similar, but the register addresses will most likely be different.

**Comment by Salex406** [comment]
I have tried, it stucks on "Sending 471" - Operation timed out. Why 471, what does it mean?

**Comment by DualTachyon** [comment]
That's because the registers are not the same. The code will not work as is.

**Comment by DualTachyon** [comment]
471 is RockChip terminology, I don't know why it is this number. Probably an internal documentation thing.
